image: mcr.microsoft.com/dotnet/sdk:5.0

pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script:
          - git submodule update --init
          - dotnet restore
          - dotnet build
          - dotnet test



